version: '3.4'

services: 
  # worker-app:
  #   image: worker-app
  #   build:
  #     dockerfile : elumini.worker\Dockerfile
  #   ports:
  #     - "3500:80"
  #   restart: always 
  #   depends_on:      
  #     - rabbitmq
  #     - sqlserverdb

  sqlserverdb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql1
    hostname: sqlserverdb
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "5434:1433"    

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq3
    restart: always
    ports: 
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest     